# 05 Predictive Modeling

This notebook tunes and compares multiple models for predicting `Outcome`:

1. Logistic Regression (light `C` search)
2. Regularized Logistic Regression (light `C` search)
3. Random Forest (tuned via `RandomizedSearchCV`)
4. Gradient Boosting (tuned via `RandomizedSearchCV`)
5. LightGBM with monotonic constraints (tuned via `RandomizedSearchCV`)

The workflow is leakage-safe: patient identifiers are never used as predictors, repeated IDs are kept together in train/test splits, and all imputation, scaling, and one-hot encoding are performed inside scikit-learn `Pipeline` objects during cross-validated hyperparameter search and final model fitting. The selected model is wrapped in `CalibratedClassifierCV` before saving.

Outputs:

- `reports/model_comparison.csv`
- `reports/monotonic_constraint_directions.csv`
- `models/best_model.joblib` (calibrated pipeline)
- `models/best_model_metadata.json`

In [1]:
from pathlib import Path
import json
import sys
import warnings

import numpy as np
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import GroupKFold

warnings.filterwarnings("ignore", category=UserWarning)

# Make `src` importable when running from notebooks/ without `pip install -e .`.
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "data" / "CardiacPatientData.csv").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import MODELS_DIR, RAW_DATA_PATH, REPORTS_DIR
from src.evaluation import compute_metrics
from src.modeling import (
    CV_SCORING,
    RANDOM_STATE,
    build_feature_matrix,
    build_monotone_constraints_vector,
    build_pipeline,
    build_preprocessor,
    derive_monotonic_constraints,
    fit_categorical_categories,
    get_candidate_model_specs,
    get_numeric_feature_order,
    make_leakage_safe_holdout,
    save_model,
    tune_model,
)

REPORTS_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)
MODEL_COMPARISON_PATH = REPORTS_DIR / "model_comparison.csv"
BEST_MODEL_PATH = MODELS_DIR / "best_model.joblib"
BEST_MODEL_METADATA_PATH = MODELS_DIR / "best_model_metadata.json"
ODDS_RATIO_RESULTS_PATH = REPORTS_DIR / "odds_ratio_results.csv"
MONOTONIC_CONSTRAINTS_PATH = REPORTS_DIR / "monotonic_constraint_directions.csv"
CALIBRATION_METHOD = "sigmoid"
CALIBRATION_CV_SPLITS = 5

## Load data

The raw dataset is loaded before splitting. Deterministic row-wise clinical features are added only after the train/test split so no train-set population statistics can leak into the held-out test set.

In [2]:
df = pd.read_csv(RAW_DATA_PATH)
print(f"Dataset shape: {df.shape[0]:,} rows x {df.shape[1]:,} columns")
display(df.head())

outcome_distribution = (
    df["Outcome"].value_counts(normalize=True).sort_index().to_frame("proportion")
)
outcome_distribution["count"] = df["Outcome"].value_counts().sort_index()
display(outcome_distribution)

Dataset shape: 5,906 rows x 20 columns

,ID,SBP,DBP,HR,RR,BT,SpO2,Age,Gender,GCS,Na,K,Cl,Urea,Ceratinine,Alcoholic,Smoke,FHCD,TriageScore,Outcome
0,1,163,95,90,18,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
1,1,134,85,85,15,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
2,1,121,77,80,19,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
3,1,103,78,70,16,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
4,1,96,70,59,13,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1

         proportion  count
Outcome
0          0.144429    853
1          0.855571   5053

## Leakage safe train/test split

Repeated `ID` values indicate multiple rows per patient. If IDs repeat, a `StratifiedGroupKFold` split is used so all observations for the same patient stay entirely in either train or test. If IDs do not repeat, the notebook falls back to a standard stratified split.

In [3]:
train_raw, test_raw, groups_train, split_strategy = make_leakage_safe_holdout(df)
overlapping_ids = set(train_raw["ID"]).intersection(test_raw["ID"])

print(f"Split strategy: {split_strategy}")
print(f"Train rows: {len(train_raw):,}; test rows: {len(test_raw):,}")
print(
    f"Train unique IDs: {train_raw['ID'].nunique():,}; "
    f"test unique IDs: {test_raw['ID'].nunique():,}"
)
print(f"Overlapping IDs across train/test: {len(overlapping_ids):,}")

display(
    pd.concat(
        {
            "train": train_raw["Outcome"].value_counts(normalize=True).sort_index(),
            "test": test_raw["Outcome"].value_counts(normalize=True).sort_index(),
        },
        axis=1,
    ).rename_axis("Outcome")
)

Split strategy: StratifiedGroupKFold by patient ID
Train rows: 4,826; test rows: 1,080
Train unique IDs: 90; test unique IDs: 22
Overlapping IDs across train/test: 0

            train      test
Outcome
0        0.150228  0.118519
1        0.849772  0.881481

## Feature engineering and preprocessing

`ID` is removed from the modeling matrix to avoid memorization. Numerical and categorical preprocessing is defined inside a `ColumnTransformer`, which is then embedded in every model pipeline. Categorical one-hot category levels are fixed from the full training set (see the cell below) rather than rediscovered independently in every cross-validation fold, so the LightGBM candidate's fixed-length `monotone_constraints` vector stays valid regardless of which fold it is fit on. Numeric imputation/scaling are still refit independently inside each fold.

In [4]:
X_train = build_feature_matrix(train_raw.drop(columns=["Outcome"]))
X_test = build_feature_matrix(test_raw.drop(columns=["Outcome"]))
y_train = train_raw["Outcome"].astype(int)
y_test = test_raw["Outcome"].astype(int)

print(f"Feature matrix: {X_train.shape[1]} columns, {len(X_train):,} training rows")

Feature matrix: 28 columns, 4,826 training rows

## Monotonic constraints, hyperparameter tuning, and model comparison

Each candidate model is wrapped in the shared preprocessing pipeline (`src.modeling.build_pipeline`) and tuned with `src.modeling.tune_model`, which runs a patient-grouped `RandomizedSearchCV` (`GroupKFold`, so no patient's rows span a search fold). The two logistic baselines get a light search over `C`; Random Forest, Gradient Boosting, and a new LightGBM candidate get wider grids (see `src.modeling.get_candidate_model_specs`).

The LightGBM candidate is fit with monotonic constraints derived from the adjusted odds-ratio model in `reports/odds_ratio_results.csv`: a statistically significant (p < 0.05) positive adjusted coefficient constrains the feature to a non-decreasing effect on predicted risk, a significant negative coefficient to non-increasing, and every other numeric feature (including the 9 not covered by the adjusted model) is left **unconstrained** rather than guessed from textbook physiology -- the adjusted model itself found some directions that run counter to naive clinical intuition (e.g. higher HR/RR/Age associated with *lower* odds of the coded `Outcome=1`), and the positive-class meaning of `Outcome` is not independently confirmed (see `reports/final_report.md`). If that meaning is later clarified and found to be inverted, every constraint sign below must be flipped. The full mapping (feature, source, coefficient, p-value, constraint) is saved to `reports/monotonic_constraint_directions.csv` for traceability.

Models are ranked by **mean cross-validated AUROC** from each search's best configuration; held-out test metrics are reported alongside for transparency but are not used for model selection.

In [5]:
odds_ratio_results = pd.read_csv(ODDS_RATIO_RESULTS_PATH)
numeric_feature_order = get_numeric_feature_order(X_train)
numeric_signs = derive_monotonic_constraints(odds_ratio_results, numeric_feature_order)

categorical_categories = fit_categorical_categories(X_train)
monotone_constraints = build_monotone_constraints_vector(
    X_train, numeric_signs, categorical_categories
)

adjusted_model = odds_ratio_results[
    odds_ratio_results["model"] == "Adjusted clinical model"
].set_index("predictor")

monotonic_constraint_directions = pd.DataFrame(
    {"feature": numeric_feature_order, "constraint": numeric_signs}
)
monotonic_constraint_directions["source"] = monotonic_constraint_directions["feature"].map(
    lambda feature: "Adjusted clinical model" if feature in adjusted_model.index else "not covered"
)
monotonic_constraint_directions["coefficient"] = monotonic_constraint_directions["feature"].map(
    lambda feature: adjusted_model.loc[feature, "coefficient"] if feature in adjusted_model.index else np.nan
)
monotonic_constraint_directions["p_value"] = monotonic_constraint_directions["feature"].map(
    lambda feature: adjusted_model.loc[feature, "p_value"] if feature in adjusted_model.index else np.nan
)
monotonic_constraint_directions.to_csv(MONOTONIC_CONSTRAINTS_PATH, index=False)

print(f"Saved monotonic constraint directions to: {MONOTONIC_CONSTRAINTS_PATH}")
display(monotonic_constraint_directions)

# Rebuild the preprocessor with fixed one-hot category levels (see cell above)
# so every tuning fold produces an identically-shaped transformed matrix.
preprocessor = build_preprocessor(X_train, categorical_categories=categorical_categories)

candidate_specs = get_candidate_model_specs(
    preprocessor, monotone_constraints=monotone_constraints
)
print(f"Comparing {len(candidate_specs)} candidate models with patient-grouped, tuned CV.")

Saved monotonic constraint directions to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/monotonic_constraint_directions.csv

,feature,constraint,source,coefficient,p_value
0,SBP,1,Adjusted clinical model,0.042785,4.987512e-17
1,DBP,0,not covered,NaN,NaN
2,HR,-1,Adjusted clinical model,-0.094607,7.911866e-50
3,RR,-1,Adjusted clinical model,-0.090520,7.147004e-11
4,BT,0,not covered,NaN,NaN
5,SpO2,1,Adjusted clinical model,0.131450,5.065316e-07
6,Age,-1,Adjusted clinical model,-0.030015,2.681261e-05
7,GCS,0,Adjusted clinical model,-0.003290,7.440815e-01
8,Na,0,not covered,NaN,NaN
9,K,0,not covered,NaN,NaN
10,Cl,0,not covered,NaN,NaN
11,Urea,0,not covered,NaN,NaN
12,Ceratinine,0,not covered,NaN,NaN
13,pulse_pressure,0,not covered,NaN,NaN
14,shock_index,0,not covered,NaN,NaN

Comparing 5 candidate models with patient-grouped, tuned CV.

In [6]:
results = []
fitted_models = {}

for model_name, spec in candidate_specs.items():
    print(f"Tuning {model_name} ({spec['n_iter']} search iterations)...")
    search = tune_model(
        spec["pipeline"],
        param_distributions=spec["param_distributions"],
        X_train=X_train,
        y_train=y_train,
        cv_groups=groups_train,
        n_splits=5,
        n_iter=spec["n_iter"],
        scoring=CV_SCORING,
    )
    cv_results = search.cv_results_
    best_index = search.best_index_

    pipeline = search.best_estimator_
    fitted_models[model_name] = pipeline

    y_score = pipeline.predict_proba(X_test)[:, 1]
    test_metrics = compute_metrics(y_test, y_score, threshold=0.5)

    results.append(
        {
            "model": model_name,
            "cv_strategy": "GroupKFold (RandomizedSearchCV)",
            "n_iter": spec["n_iter"],
            "best_params": json.dumps(search.best_params_, default=str),
            "cv_mean_auroc": cv_results["mean_test_auroc"][best_index],
            "cv_std_auroc": cv_results["std_test_auroc"][best_index],
            "cv_mean_auprc": cv_results["mean_test_auprc"][best_index],
            "cv_mean_f1": cv_results["mean_test_f1"][best_index],
            "cv_mean_sensitivity": cv_results["mean_test_sensitivity"][best_index],
            "test_auroc": test_metrics["auroc"],
            "test_auprc": test_metrics["auprc"],
            "test_f1": test_metrics["f1"],
            "test_sensitivity": test_metrics["sensitivity"],
            "test_specificity": test_metrics["specificity"],
            "test_ppv": test_metrics["ppv"],
            "test_npv": test_metrics["npv"],
            "test_brier": test_metrics["brier_score"],
        }
    )

comparison_df = (
    pd.DataFrame(results)
    .sort_values(by=["cv_mean_auroc", "cv_mean_auprc"], ascending=False)
    .reset_index(drop=True)
)
comparison_df["rank_by_cv_auroc"] = np.arange(1, len(comparison_df) + 1)
comparison_df.to_csv(MODEL_COMPARISON_PATH, index=False)

print(f"Saved model comparison table to: {MODEL_COMPARISON_PATH}")
display(comparison_df)

Tuning Logistic Regression (10 search iterations)...

Tuning Regularized Logistic Regression (5 search iterations)...

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

Tuning Random Forest (10 search iterations)...

Tuning Gradient Boosting (10 search iterations)...

Tuning LightGBM (monotonic) (12 search iterations)...

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Saved model comparison table to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/model_comparison.csv

/tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/.venv/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

,model,cv_strategy,n_iter,best_params,cv_mean_auroc,cv_std_auroc,cv_mean_auprc,cv_mean_f1,cv_mean_sensitivity,test_auroc,test_auprc,test_f1,test_sensitivity,test_specificity,test_ppv,test_npv,test_brier,rank_by_cv_auroc
0,Regularized Logistic Regression,GroupKFold (RandomizedSearchCV),5,"{""model__C"": 0.31489116479568624}",0.898422,0.064350,0.975324,0.849546,0.807898,0.699744,0.940135,0.869321,0.814076,0.562500,0.932611,0.289157,0.169819,1
1,Logistic Regression,GroupKFold (RandomizedSearchCV),10,"{""model__C"": 0.31489116479568624}",0.894832,0.055079,0.973792,0.902299,0.922351,0.724166,0.947230,0.928230,0.917017,0.562500,0.939720,0.476821,0.107772,2
2,Gradient Boosting,GroupKFold (RandomizedSearchCV),10,"{""model__learning_rate"": 0.03574712922600244, ...",0.880485,0.062279,0.978690,0.878361,0.898957,0.889616,0.983407,0.955394,0.967437,0.570312,0.943648,0.701923,0.070776,3
3,LightGBM (monotonic),GroupKFold (RandomizedSearchCV),12,"{""model__learning_rate"": 0.017240892195821537,...",0.869360,0.115786,0.970292,0.905917,0.951544,0.750168,0.961398,0.900358,0.925420,0.031250,0.876617,0.053333,0.115854,4
4,Random Forest,GroupKFold (RandomizedSearchCV),10,"{""model__n_estimators"": 200, ""model__min_sampl...",0.864650,0.043212,0.970931,0.911961,0.972116,0.869855,0.978805,0.940620,0.940126,0.562500,0.941115,0.558140,0.080113,5

## Calibrate and save the best model

The best model is selected by mean cross-validated AUROC, with AUPRC used as a tie-breaker. Its raw predicted probabilities are not necessarily well-calibrated (tree ensembles in particular tend to produce overconfident scores), so before saving, the winning pipeline is wrapped in a `CalibratedClassifierCV` (sigmoid/Platt scaling, chosen over isotonic regression because the effective sample size here is only ~112 patients -- isotonic's non-parametric fit is prone to instability at this scale, while Platt's 2-parameter logistic fit is far more stable). Calibration uses the same patient-grouped `GroupKFold` splits as tuning, so no patient's rows leak between a calibration fold's training and held-out portions.

The saved object is the complete, calibrated scikit-learn pipeline, so future scoring applies the same preprocessing, model, and calibration steps before prediction. A small `models/best_model_metadata.json` sidecar records the calibration method, monotonic constraints, and winning hyperparameters for downstream notebooks.

In [7]:
best_model_name = comparison_df.loc[0, "model"]
best_model = fitted_models[best_model_name]

print(f"Best model (by cross-validated AUROC): {best_model_name}")
display(
    comparison_df.loc[
        0,
        [
            "model",
            "cv_mean_auroc",
            "test_auroc",
            "test_auprc",
            "test_f1",
            "test_sensitivity",
            "test_specificity",
            "test_ppv",
            "test_npv",
        ],
    ].to_frame("value")
)

Best model (by cross-validated AUROC): Regularized Logistic Regression

                                            value
model             Regularized Logistic Regression
cv_mean_auroc                            0.898422
test_auroc                               0.699744
test_auprc                               0.940135
test_f1                                  0.869321
test_sensitivity                         0.814076
test_specificity                           0.5625
test_ppv                                 0.932611
test_npv                                 0.289157

In [8]:
# Materialize the GroupKFold split explicitly: CalibratedClassifierCV.fit() has
# no `groups=` parameter, so patient-grouped folds must be passed as a list of
# (train_idx, test_idx) pairs to keep calibration leakage-safe.
calibration_cv = list(
    GroupKFold(n_splits=CALIBRATION_CV_SPLITS).split(
        X_train, y_train, groups=groups_train
    )
)
calibrated_model = CalibratedClassifierCV(
    best_model, method=CALIBRATION_METHOD, cv=calibration_cv
)
calibrated_model.fit(X_train, y_train)

save_model(calibrated_model, BEST_MODEL_PATH)
print(f"Saved calibrated best model pipeline to: {BEST_MODEL_PATH}")

best_model_metadata = {
    "best_model_name": best_model_name,
    "calibration_method": CALIBRATION_METHOD,
    "calibration_cv_splits": CALIBRATION_CV_SPLITS,
    "best_params": comparison_df.loc[0, "best_params"],
    "monotone_constraints": monotone_constraints,
    "numeric_feature_order": numeric_feature_order,
}
with open(BEST_MODEL_METADATA_PATH, "w") as f:
    json.dump(best_model_metadata, f, indent=2)
print(f"Saved model metadata to: {BEST_MODEL_METADATA_PATH}")

# Recompute held-out metrics using the *calibrated* probabilities, since these
# are what downstream notebooks (06, 07) will actually load and score with.
y_score_calibrated = calibrated_model.predict_proba(X_test)[:, 1]
calibrated_test_metrics = compute_metrics(y_test, y_score_calibrated, threshold=0.5)
print("Held-out test metrics after calibration:")
display(pd.Series(calibrated_test_metrics).to_frame("value"))

Saved calibrated best model pipeline to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/models/best_model.joblib
Saved model metadata to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/models/best_model_metadata.json
Held-out test metrics after calibration:

                     value
auroc             0.698513
auprc             0.939760
sensitivity       0.972689
specificity       0.531250
ppv               0.939148
npv               0.723404
brier_score       0.087152
threshold         0.500000
f1                0.955624
flagged         986.000000
flagged_pct       0.912963
true_negative    68.000000
false_positive   60.000000
false_negative   26.000000
true_positive   926.000000

## Interpretation, model performance and complexity

The cell below prints a short interpretation from the saved comparison table. In this workflow, added model complexity is considered justified only when a more complex model materially improves held-out AUROC/AUPRC over the simpler logistic baselines and does not sacrifice clinically important sensitivity or NPV.

In [9]:
best = comparison_df.iloc[0]
logistic_mask = comparison_df["model"].isin(
    ["Logistic Regression", "Regularized Logistic Regression"]
)
logistic_best = comparison_df[logistic_mask].iloc[0]
auroc_gain = best["test_auroc"] - logistic_best["test_auroc"]
auprc_gain = best["test_auprc"] - logistic_best["test_auprc"]

if best["model"] == logistic_best["model"]:
    complexity_statement = (
        "The best-performing model is a logistic baseline, so additional "
        "tree-based complexity is not justified by this evaluation."
    )
elif auroc_gain >= 0.02 or auprc_gain >= 0.02:
    complexity_statement = (
        "The added complexity appears justified: the best non-logistic model "
        "improves AUROC or AUPRC by at least 0.02 over the best logistic baseline."
    )
else:
    complexity_statement = (
        "The added complexity is only weakly justified: the improvement over the "
        "best logistic baseline is small (<0.02 AUROC and AUPRC)."
    )

print(
    f"Best model: {best['model']} "
    f"(test AUROC={best['test_auroc']:.3f}, AUPRC={best['test_auprc']:.3f}, "
    f"F1={best['test_f1']:.3f}, sensitivity={best['test_sensitivity']:.3f}, "
    f"specificity={best['test_specificity']:.3f}, PPV={best['test_ppv']:.3f}, "
    f"NPV={best['test_npv']:.3f})."
)
print(
    f"Best logistic baseline: {logistic_best['model']} "
    f"(test AUROC={logistic_best['test_auroc']:.3f}, "
    f"AUPRC={logistic_best['test_auprc']:.3f})."
)
print(
    f"Difference vs best logistic baseline: "
    f"AUROC={auroc_gain:.3f}, AUPRC={auprc_gain:.3f}."
)
print(complexity_statement)

Best model: Regularized Logistic Regression (test AUROC=0.700, AUPRC=0.940, F1=0.869, sensitivity=0.814, specificity=0.562, PPV=0.933, NPV=0.289).
Best logistic baseline: Regularized Logistic Regression (test AUROC=0.700, AUPRC=0.940).
Difference vs best logistic baseline: AUROC=0.000, AUPRC=0.000.
The best-performing model is a logistic baseline, so additional tree-based complexity is not justified by this evaluation.

## Results summary

Models are tuned and ranked by mean cross-validated AUROC in
`reports/model_comparison.csv`. The top configuration is refit on the full
training split, wrapped in a `CalibratedClassifierCV` (sigmoid/Platt scaling),
and saved to `models/best_model.joblib` (with tuning/calibration provenance in
`models/best_model_metadata.json`). The selected model balances discrimination
(AUROC/AUPRC) against clinically important sensitivity and NPV, and the
interpretation cell above flags whether any added tree-based complexity is
justified over the regularized logistic baseline. Re-running this notebook
regenerates the comparison table, the monotonic-constraint directions table,
and the saved calibrated model.