# 06 Final Model Evaluation

This notebook loads `models/best_model.joblib` and evaluates the saved model pipeline on the same leakage-safe held-out test split used during predictive modeling.

Outputs:

- `reports/final_model_metrics.csv`
- `reports/threshold_analysis.csv`
- Figures saved under `reports/figures/`

In [1]:
from pathlib import Path
import json
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import average_precision_score, confusion_matrix, roc_auc_score

# Make `src` importable when running from notebooks/ without `pip install -e .`.
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "data" / "CardiacPatientData.csv").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import FIGURES_DIR, MODELS_DIR, RAW_DATA_PATH, REPORTS_DIR
from src.evaluation import (
    bootstrap_ci,
    compute_calibration_slope_intercept,
    compute_metrics,
    compute_net_benefit,
    plot_calibration_curve,
    plot_decision_curve,
    plot_roc_pr,
)
from src.modeling import build_feature_matrix, load_model, make_leakage_safe_holdout

REPORTS_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
MODEL_PATH = MODELS_DIR / "best_model.joblib"
BEST_MODEL_METADATA_PATH = MODELS_DIR / "best_model_metadata.json"
FINAL_METRICS_PATH = REPORTS_DIR / "final_model_metrics.csv"
THRESHOLD_ANALYSIS_PATH = REPORTS_DIR / "threshold_analysis.csv"
sns.set_theme(style="whitegrid")

## Load data, recreate the held out test set, and score the saved model

The split logic mirrors `notebooks/05_predictive_modeling.ipynb`: repeated `ID` values are kept together with `StratifiedGroupKFold`; otherwise, a stratified row-wise split is used. Clinical features are deterministic row-level features and are added after splitting. `ID` is removed before prediction to avoid identifier leakage.

In [2]:
model = load_model(MODEL_PATH)
df = pd.read_csv(RAW_DATA_PATH)

if BEST_MODEL_METADATA_PATH.exists():
    with open(BEST_MODEL_METADATA_PATH) as f:
        best_model_metadata = json.load(f)
    calibration_method = best_model_metadata.get("calibration_method", "unknown")
else:
    best_model_metadata = {}
    calibration_method = "unknown"

train_raw, test_raw, groups_train, split_strategy = make_leakage_safe_holdout(df)
X_test = build_feature_matrix(test_raw.drop(columns=["Outcome"]))
y_test = test_raw["Outcome"].astype(int)
test_groups = test_raw["ID"].to_numpy()

y_score = model.predict_proba(X_test)[:, 1]

print(f"Model loaded from: {MODEL_PATH}")
print(f"Calibration method (from {BEST_MODEL_METADATA_PATH.name}): {calibration_method}")
print(f"Split strategy: {split_strategy}")
print(f"Test rows: {len(test_raw):,}")
print(f"Test event rate: {y_test.mean():.3f}")
print(f"Score range: {y_score.min():.3f} to {y_score.max():.3f}")

Model loaded from: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/models/best_model.joblib
Calibration method (from best_model_metadata.json): sigmoid
Split strategy: StratifiedGroupKFold by patient ID
Test rows: 1,080
Test event rate: 0.881
Score range: 0.193 to 0.999

## Threshold analysis

The table below evaluates clinically relevant tradeoffs across probability thresholds. Sensitivity is prioritized for a high-risk screening flag, while specificity and PPV quantify the false alarm burden. Two complementary lenses are reported: a sensitivity-first clinical rule (used as the primary recommended threshold) and, separately, the threshold that maximizes decision-curve net benefit (see the calibration/decision-curve section below for the full curve).

In [3]:
thresholds = np.round(np.arange(0.05, 0.96, 0.05), 2)
threshold_columns = [
    "threshold",
    "sensitivity",
    "specificity",
    "ppv",
    "npv",
    "f1",
    "flagged",
    "flagged_pct",
    "true_negative",
    "false_positive",
    "false_negative",
    "true_positive",
]
rows = []
for t in thresholds:
    m = compute_metrics(y_test, y_score, threshold=t)
    rows.append({key: m[key] for key in threshold_columns})
threshold_df = pd.DataFrame(rows)

# Clinical rule: keep at least 90% sensitivity when possible, then pick the
# highest such threshold to limit false alarms; otherwise pick best F1.
sensitive = threshold_df[threshold_df["sensitivity"] >= 0.90]
if len(sensitive):
    recommended_row = sensitive.sort_values(
        ["threshold", "specificity", "ppv"], ascending=False
    ).iloc[0]
    recommendation_rule = (
        "highest threshold with sensitivity >= 0.90 to limit false alarms"
    )
else:
    recommended_row = threshold_df.sort_values(
        ["f1", "sensitivity"], ascending=False
    ).iloc[0]
    recommendation_rule = "highest F1 because no threshold achieved sensitivity >= 0.90"

recommended_threshold = float(recommended_row["threshold"])
threshold_df["recommended"] = threshold_df["threshold"].eq(recommended_threshold)
threshold_df.to_csv(THRESHOLD_ANALYSIS_PATH, index=False)

# Second, complementary lens: the threshold that maximizes decision-curve net
# benefit (see src.evaluation.compute_net_benefit). This does not replace the
# sensitivity-first clinical rule above -- it is reported alongside so the two
# lenses can be compared.
net_benefit_df = compute_net_benefit(y_test.to_numpy(), y_score, thresholds)
best_net_benefit_idx = net_benefit_df["net_benefit_model"].idxmax()
net_benefit_max_threshold = float(net_benefit_df.loc[best_net_benefit_idx, "threshold"])
net_benefit_max_value = float(net_benefit_df.loc[best_net_benefit_idx, "net_benefit_model"])

print(f"Saved threshold analysis to: {THRESHOLD_ANALYSIS_PATH}")
print(
    f"Recommended threshold (sensitivity-first rule): {recommended_threshold:.2f} "
    f"({recommendation_rule})"
)
print(
    f"Net-benefit-maximizing threshold (decision-curve lens): "
    f"{net_benefit_max_threshold:.2f} (net benefit={net_benefit_max_value:.4f})"
)
display(threshold_df)

Saved threshold analysis to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/threshold_analysis.csv
Recommended threshold (sensitivity-first rule): 0.70 (highest threshold with sensitivity >= 0.90 to limit false alarms)
Net-benefit-maximizing threshold (decision-curve lens): 0.05 (net benefit=0.8752)

,threshold,sensitivity,specificity,ppv,npv,f1,flagged,flagged_pct,true_negative,false_positive,false_negative,true_positive,recommended
0,0.05,1.000000,0.000000,0.881481,NaN,0.937008,1080,1.000000,0,128,0,952,False
1,0.10,1.000000,0.000000,0.881481,NaN,0.937008,1080,1.000000,0,128,0,952,False
2,0.15,1.000000,0.000000,0.881481,NaN,0.937008,1080,1.000000,0,128,0,952,False
3,0.20,0.998950,0.000000,0.881372,0.000000,0.936484,1079,0.999074,0,128,1,951,False
4,0.25,0.997899,0.007812,0.882080,0.333333,0.936422,1077,0.997222,1,127,2,950,False
5,0.30,0.994748,0.007812,0.881750,0.166667,0.934847,1074,0.994444,1,127,5,947,False
6,0.35,0.991597,0.101562,0.891407,0.619048,0.938836,1059,0.980556,13,115,8,944,False
7,0.40,0.985294,0.296875,0.912451,0.730769,0.947475,1028,0.951852,38,90,14,938,False
8,0.45,0.976891,0.437500,0.928144,0.717949,0.951894,1002,0.927778,56,72,22,930,False
9,0.50,0.972689,0.531250,0.939148,0.723404,0.955624,986,0.912963,68,60,26,926,False
10,0.55,0.967437,0.546875,0.940756,0.693069,0.953910,979,0.906481,70,58,31,921,False
11,0.60,0.956933,0.562500,0.942089,0.637168,0.949453,967,0.895370,72,56,41,911,False
12,0.65,0.947479,0.562500,0.941545,0.590164,0.944503,958,0.887037,72,56,50,902,False
13,0.70,0.922269,0.562500,0.940043,0.493151,0.931071,934,0.864815,72,56,74,878,True
14,0.75,0.880252,0.562500,0.937360,0.387097,0.907909,894,0.827778,72,56,114,838,False
15,0.80,0.810924,0.562500,0.932367,0.285714,0.867416,828,0.766667,72,56,180,772,False
16,0.85,0.695378,0.562500,0.922006,0.198895,0.792814,718,0.664815,72,56,290,662,False
17,0.90,0.565126,0.562500,0.905724,0.148148,0.695990,594,0.550000,72,56,414,538,False
18,0.95,0.385504,0.578125,0.871734,0.112291,0.534596,421,0.389815,74,54,585,367,False

## Discrimination, calibration, and patient-level bootstrap CIs

Headline metrics are reported with **95% confidence intervals from a
patient-level bootstrap** (`src.evaluation.bootstrap_ci`). Because a single
patient can contribute hundreds of rows, the bootstrap resamples unique patient
IDs (not rows) on the held-out test set only, so the intervals reflect the true
number of independent patients rather than the inflated row count.

In [4]:
fig, _ = plot_roc_pr(y_test, y_score)
roc_pr_path = FIGURES_DIR / "final_model_roc_pr_curves.png"
fig.savefig(roc_pr_path, dpi=300, bbox_inches="tight")
plt.show()

# Patient-level bootstrap 95% CIs on the held-out test set. Sensitivity,
# specificity, and net benefit are evaluated at the recommended operating
# threshold; AUROC, AUPRC, Brier score, and calibration slope are
# threshold-independent (calibration slope is refit inside every bootstrap
# resample, same as the other metrics).
N_BOOT = 1000
metric_fns = {
    "auroc": roc_auc_score,
    "auprc": average_precision_score,
    "sensitivity": lambda yt, yp: compute_metrics(yt, yp, recommended_threshold)[
        "sensitivity"
    ],
    "specificity": lambda yt, yp: compute_metrics(yt, yp, recommended_threshold)[
        "specificity"
    ],
    "brier_score": lambda yt, yp: compute_metrics(yt, yp)["brier_score"],
    "calibration_slope": lambda yt, yp: compute_calibration_slope_intercept(yt, yp)[1],
    "net_benefit": lambda yt, yp: compute_net_benefit(
        yt, yp, np.array([recommended_threshold])
    )["net_benefit_model"].iloc[0],
}

ci = {}
for name, fn in metric_fns.items():
    point, lower, upper = bootstrap_ci(
        y_test.to_numpy(), y_score, fn, groups=test_groups, n_boot=N_BOOT
    )
    ci[name] = {"point": point, "lower": lower, "upper": upper}


def fmt_ci(name):
    """Format as e.g. ``0.82 (95% CI: 0.74-0.89)``."""
    c = ci[name]
    return f"{c['point']:.2f} (95% CI: {c['lower']:.2f}\u2013{c['upper']:.2f})"


n_patients = int(pd.Series(test_groups).nunique())
print(f"Saved ROC/PR curves to: {roc_pr_path}")
print(
    f"Held-out test set: {len(y_test):,} rows from {n_patients} unique patients "
    f"({N_BOOT} patient-level bootstrap resamples)."
)
print(f"Operating threshold for sensitivity/specificity/net benefit: {recommended_threshold:.2f}")
for name in metric_fns:
    print(f"  {name:18s}: {fmt_ci(name)}")

Saved ROC/PR curves to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/figures/final_model_roc_pr_curves.png
Held-out test set: 1,080 rows from 22 unique patients (1000 patient-level bootstrap resamples).
Operating threshold for sensitivity/specificity/net benefit: 0.70
  auroc             : 0.70 (95% CI: 0.18–0.99)
  auprc             : 0.94 (95% CI: 0.78–1.00)
  sensitivity       : 0.92 (95% CI: 0.82–0.98)
  specificity       : 0.56 (95% CI: 0.00–0.97)
  brier_score       : 0.09 (95% CI: 0.03–0.20)
  calibration_slope : 0.57 (95% CI: -0.49–4.62)
  net_benefit       : 0.69 (95% CI: 0.27–0.90)

## Calibration and decision-curve assessment

Net benefit's "treat" framing assumes `Outcome=1` is the adverse event that a high-risk flag should prompt intervention for. The exact clinical meaning and positive-class direction of `Outcome` are not independently confirmed (see `reports/final_report.md`); if that meaning is later clarified and found to be inverted, this framing -- and the sensitivity-first threshold rule above -- would need to be re-derived under the opposite assumption.

In [5]:
brier = compute_metrics(y_test, y_score)["brier_score"]

ax = plot_calibration_curve(y_test, y_score, n_bins=10)
calibration_path = FIGURES_DIR / "final_model_calibration_curve.png"
ax.figure.savefig(calibration_path, dpi=300, bbox_inches="tight")
plt.show()

calibration_intercept, calibration_slope = compute_calibration_slope_intercept(
    y_test, y_score
)

ax_dc = plot_decision_curve(y_test, y_score, thresholds)
decision_curve_path = FIGURES_DIR / "final_model_decision_curve.png"
ax_dc.figure.savefig(decision_curve_path, dpi=300, bbox_inches="tight")
plt.show()

print(f"Brier score: {brier:.4f}")
print(f"Calibration intercept: {calibration_intercept:.4f}")
print(f"Calibration slope: {calibration_slope:.4f}")
print(f"Saved calibration curve to: {calibration_path}")
print(f"Saved decision curve to: {decision_curve_path}")

Brier score: 0.0872
Calibration intercept: 0.8423
Calibration slope: 0.5745
Saved calibration curve to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/figures/final_model_calibration_curve.png
Saved decision curve to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/figures/final_model_decision_curve.png

## Confusion matrices at multiple thresholds

In [6]:
thresholds_to_plot = sorted({0.10, 0.20, recommended_threshold, 0.50, 0.80})
n_cols = min(3, len(thresholds_to_plot))
n_rows = int(np.ceil(len(thresholds_to_plot) / n_cols))
fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 4.5 * n_rows))
axes = np.atleast_1d(axes).ravel()

for ax, threshold in zip(axes, thresholds_to_plot):
    y_pred = (y_score >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        cbar=False,
        xticklabels=["Predicted low", "Predicted high"],
        yticklabels=["Actual low", "Actual high"],
        ax=ax,
    )
    suffix = " (recommended)" if np.isclose(threshold, recommended_threshold) else ""
    ax.set_title(f"Threshold {threshold:.2f}{suffix}")
    ax.set_xlabel("Predicted class")
    ax.set_ylabel("Actual class")

for ax in axes[len(thresholds_to_plot):]:
    ax.axis("off")

fig.suptitle("Held-out confusion matrices across thresholds", y=1.02, fontsize=16)
fig.tight_layout()
confusion_path = FIGURES_DIR / "final_model_confusion_matrices.png"
fig.savefig(confusion_path, dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved confusion matrices to: {confusion_path}")

Saved confusion matrices to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/figures/final_model_confusion_matrices.png

## Final metrics and clinical threshold recommendation

In [7]:
def ci_columns(name):
    c = ci[name]
    return {
        name: c["point"],
        f"{name}_lower": c["lower"],
        f"{name}_upper": c["upper"],
    }


rec = recommended_row.to_dict()
final_metrics = {
    "model_path": str(MODEL_PATH),
    "calibration_method": calibration_method,
    "split_strategy": split_strategy,
    "test_rows": len(test_raw),
    "test_patients": int(pd.Series(test_groups).nunique()),
    "test_event_rate": float(y_test.mean()),
    "threshold": recommended_threshold,
    "recommendation_rule": recommendation_rule,
    "net_benefit_max_threshold": net_benefit_max_threshold,
    "n_boot": N_BOOT,
    "ci_method": "patient-level (group) bootstrap, 2.5/97.5 percentiles",
    **ci_columns("auroc"),
    **ci_columns("auprc"),
    **ci_columns("sensitivity"),
    **ci_columns("specificity"),
    **ci_columns("brier_score"),
    **ci_columns("calibration_slope"),
    **ci_columns("net_benefit"),
    "calibration_intercept": calibration_intercept,
    "recommended_ppv": rec["ppv"],
    "recommended_npv": rec["npv"],
    "recommended_flagged_high_risk": int(rec["flagged"]),
    "recommended_flagged_high_risk_pct": rec["flagged_pct"],
}
final_metrics_df = pd.DataFrame([final_metrics])
final_metrics_df.to_csv(FINAL_METRICS_PATH, index=False)

print(f"Saved final metrics to: {FINAL_METRICS_PATH}")
display(final_metrics_df.T.rename(columns={0: "value"}))

headline = ", ".join(f"{name} {fmt_ci(name)}" for name in metric_fns)
recommendation_text = (
    f"At the recommended threshold of {recommended_threshold:.2f} "
    f"('{recommendation_rule}'), the model flags {int(rec['flagged'])} of "
    f"{len(y_test)} held-out patients ({rec['flagged_pct']:.1%}) as high risk. "
    f"The decision-curve net-benefit-maximizing threshold is "
    f"{net_benefit_max_threshold:.2f}. "
    f"Headline held-out performance with patient-level 95% CIs: {headline}. "
    "All intervals come from resampling patients (not rows); validate with "
    "clinicians and recalibrate prospectively before any operational use."
)
print(recommendation_text)

Saved final metrics to: /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-Modeling/690dac66-e2b0-5b14-9947-8e111df2d6e5/scratchpad/work/reports/final_model_metrics.csv

                                                                               value
model_path                         /tmp/claude-0/-home-user-Cardiac-Arrest-Risk-M...
calibration_method                                                           sigmoid
split_strategy                                    StratifiedGroupKFold by patient ID
test_rows                                                                       1080
test_patients                                                                     22
test_event_rate                                                             0.881481
threshold                                                                        0.7
recommendation_rule                highest threshold with sensitivity >= 0.90 to ...
net_benefit_max_threshold                                                       0.05
n_boot                                                                          1000
ci_method                          patient-level (group) bootstrap, 2.5/97.5 perc...
auroc                                                                       0.698513
auroc_lower                                                                 0.184601
auroc_upper                                                                 0.987097
auprc                                                                        0.93976
auprc_lower                                                                 0.784014
auprc_upper                                                                 0.998428
sensitivity                                                                 0.922269
sensitivity_lower                                                           0.823586
sensitivity_upper                                                           0.983774
specificity                                                                   0.5625
specificity_lower                                                                0.0
specificity_upper                                                           0.972973
brier_score                                                                 0.087152
brier_score_lower                                                           0.029098
brier_score_upper                                                           0.197242
calibration_slope                                                           0.574484
calibration_slope_lower                                                    -0.489905
calibration_slope_upper                                                     4.624044
net_benefit                                                                 0.691975
net_benefit_lower                                                           0.268406
net_benefit_upper                                                           0.897337
calibration_intercept                                                       0.842301
recommended_ppv                                                             0.940043
recommended_npv                                                             0.493151
recommended_flagged_high_risk                                                    934
recommended_flagged_high_risk_pct                                           0.864815

At the recommended threshold of 0.70 ('highest threshold with sensitivity >= 0.90 to limit false alarms'), the model flags 934 of 1080 held-out patients (86.5%) as high risk. The decision-curve net-benefit-maximizing threshold is 0.05. Headline held-out performance with patient-level 95% CIs: auroc 0.70 (95% CI: 0.18–0.99), auprc 0.94 (95% CI: 0.78–1.00), sensitivity 0.92 (95% CI: 0.82–0.98), specificity 0.56 (95% CI: 0.00–0.97), brier_score 0.09 (95% CI: 0.03–0.20), calibration_slope 0.57 (95% CI: -0.49–4.62), net_benefit 0.69 (95% CI: 0.27–0.90). All intervals come from resampling patients (not rows); validate with clinicians and recalibrate prospectively before any operational use.

## Conclusion

This notebook evaluated the final model on the held-out test set to measure how well it performs on unseen patient data. The evaluation focused on discrimination, calibration, and threshold selection. AUROC and AUPRC showed how well the model separated higher-risk and lower-risk patients, while the Brier score and calibration curve assessed how reliable the predicted probabilities were. The threshold analysis was especially important because a cardiac risk model should prioritize catching high-risk patients rather than relying on the default 0.50 cutoff.

This notebook provides a final check of model performance and shows how the model could be used as a screening tool. Before any clinical use, the model would still need external validation, subgroup testing, and clinical review.